# =============================================================================
# File: /opt/ansible-k3s-cluster/inventory/group_vars/build.yml
# =============================================================================
distcc_total_jobs: 28
tmpfs_size: "3G"
